attempt 20

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,52 +23,33 @@ jobs:
             ./gradlew build --exclude-task test && ./gradlew --stop
             sleep 10
             echo "Stopping the old bot..."
-            # Останавливаем старый процесс бота
-            # pkill -f 'java -jar /***/entsogBot/build/libs/exchange_rates_bot-0.0.1-SNAPSHOT.jar' || true
-            #pkill -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' || pkill -9 -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
             if pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
-            echo "Stopping the old bot..."
-            pkill -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' || pkill -9 -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
-            
-            # Добавим небольшую паузу, чтобы дать процессу время для завершения
-            sleep 5
-          
-            # Проверяем, остановлен ли процесс
-            if pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
-            echo "Stopping the old bot..."
-            pkill -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' || pkill -9 -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
-            sleep 5
-            if ! pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
-            echo "Bot stopped successfully."
+              echo "Stopping the old bot..."
+              pkill -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' || pkill -9 -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
+              sleep 5
+              if ! pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
+                echo "Bot stopped successfully."
+              else
+                echo "Failed to stop the bot after force attempt."
+                exit 1
+              fi
             else
-            echo "Failed to stop the bot after force attempt."
-            exit 1
+              echo "No bot process found, skipping stop."
             fi
-            else
-            echo "No bot process found, skipping stop."
-            fi
-  
-  
-  
-            # Даем время для полной остановки
             echo "Checking if the bot has stopped..."
-            #pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' || echo "Bot stopped successfully."
             attempts=0
             while pgrep -f 'java.*exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; do
-            if [ $attempts -ge 5 ]; then
-            echo "Failed to stop the bot after 5 attempts."
-            exit 1
-            fi
-            echo "Waiting for the bot to stop..."
-            sleep 5
-            attempts=$((attempts+1))
+              if [ $attempts -ge 5 ]; then
+                echo "Failed to stop the bot after 5 attempts."
+                exit 1
+              fi
+              echo "Waiting for the bot to stop..."
+              sleep 5
+              attempts=$((attempts+1))
             done
-  
-  
-            #nohup java -jar /root/entsogBot/build/libs/exchange_rates_bot-0.0.1-SNAPSHOT.jar &> /dev/null &
             nohup java -jar /root/entsogBot/build/libs/exchange_rates_bot-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
             echo "Bot restarted and running in background. Checking nohup.out for output..."
-            echo "Starting the new bot... "
+            echo "Starting the new bot..."
             sleep 5
             cd /root/entsogBot/build/libs        
             echo "Bot restarted successfully!"
