attempt 18

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,16 +27,21 @@ jobs:
             # pkill -f 'java -jar /***/entsogBot/build/libs/exchange_rates_bot-0.0.1-SNAPSHOT.jar' || true
             #pkill -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' || pkill -9 -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
             if pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
-              echo "Stopping the old bot..."
-              pkill -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' || pkill -9 -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
-              if pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
-                  echo "Failed to stop the bot after force attempt."
-                  exit 1
-              else
-                echo "Bot stopped successfully."
-              fi
+            echo "Stopping the old bot..."
+            pkill -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' || pkill -9 -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
+            
+            # Добавим небольшую паузу, чтобы дать процессу время для завершения
+            sleep 5
+          
+            # Проверяем, остановлен ли процесс
+            if ! pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
+            echo "Bot stopped successfully."
             else
-                echo "No bot process found, skipping stop."
+            echo "Failed to stop the bot after force attempt."
+            exit 1
+            fi
+            else
+            echo "No bot process found, skipping stop."
             fi
   
   
