autorun 25

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,6 +23,7 @@ jobs:
             
             
             echo "Attempting to stop the old bot..."
+            process_stopped=false
             if pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
               pkill -15 -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
               sleep 10
@@ -33,22 +34,26 @@ jobs:
               fi
               if pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
                 echo "Failed to stop the bot after all attempts."
-                exit 1
               else
                 echo "Bot stopped successfully."
-                exit 0
+                process_stopped=true
               fi
             else
               echo "No bot process found, skipping stop."
-              exit 0
+              process_stopped=true
             fi
 
-            echo "Starting the new bot..."
-            ./gradlew build --exclude-task test && ./gradlew --stop
-            sleep 5
-            nohup java -jar /root/entsogBot/build/libs/exchange_rates_bot-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
-            sleep 5
-            echo "Bot restarted and running in background. Checking nohup.out for output..."
-            cd /root/entsogBot/build/libs
-            echo "Deployment successful!"
-            exit 0
+            if [ "$process_stopped" = true ]; then
+              echo "Starting the new bot..."
+              ./gradlew build --exclude-task test && ./gradlew --stop
+              sleep 5
+              nohup java -jar /root/entsogBot/build/libs/exchange_rates_bot-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
+              sleep 5
+              echo "Bot restarted and running in background. Checking nohup.out for output..."
+              cd /root/entsogBot/build/libs
+              echo "Deployment successful!"
+              exit 0
+            else
+              echo "Deployment failed due to unsuccessful bot termination."
+              exit 1
+            fi
