attempt 17

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,7 +25,22 @@ jobs:
             echo "Stopping the old bot..."
             # Останавливаем старый процесс бота
             # pkill -f 'java -jar /***/entsogBot/build/libs/exchange_rates_bot-0.0.1-SNAPSHOT.jar' || true
-            pkill -9 -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
+            #pkill -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' || pkill -9 -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
+            if pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
+              echo "Stopping the old bot..."
+              pkill -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' || pkill -9 -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar'
+              if pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' > /dev/null; then
+                  echo "Failed to stop the bot after force attempt."
+                  exit 1
+              else
+                echo "Bot stopped successfully."
+              fi
+            else
+                echo "No bot process found, skipping stop."
+            fi
+  
+  
+  
             # Даем время для полной остановки
             echo "Checking if the bot has stopped..."
             #pgrep -f 'exchange_rates_bot-0.0.1-SNAPSHOT.jar' || echo "Bot stopped successfully."
